### ISSUE TITLE
UI: Autocomplete disappearing below the screen

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/access-hive-forum-theme#16]
Bug raised by Aidan in [this slack message](https://access-nri.slack.com/archives/C056C3M1PLJ/p1723429743667539)

### Nature of the bug
When trying to tag someone in a chat conversation, the suggested autocomplete for the person disappear below the screen border and cannot be seen or accessed via scrolling.

To verify is the problem persists also with the old styling.
In any case, it needs to be fixed.

**Comment by echus** [comment]
Hi @atteggiani @aidanheerdegen, could you share a full screen screenshot of what is happening, and what browser/version you are using? I can't replicate the problem on Chrome/Chromium or Safari. This is what I see when tagging: 
![1723518034](https://github.com/user-attachments/assets/0fa070c4-4298-4e2c-b92e-afc18ec9979b)

**Comment by aidanheerdegen** [comment]
Safari Version 16.5.1 (18615.2.9.11.7)

Only reproduces when there is a single autocomplete. See how it flips below when there is only a single suggestion

![Screenshot 2024-08-13 at 1 34 00 pm](https://github.com/user-attachments/assets/01b38a9b-985e-41e7-9fce-1466a51d361f)
![Screenshot 2024-08-13 at 1 34 09 pm](https://github.com/user-attachments/assets/2f68db3b-e025-400f-8970-91cf793ddf41)

**Comment by echus** [comment]
Hi @aidanheerdegen , we've tried to recreate this issue in Browserstack with Safari 16.5 and still can't see the issue. Are others also experiencing it?

We can add a little bit of margin on the bottom of that popup for a quick fix, it just might look a little odd on browsers that aren't experiencing the issue.
